name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open NuGet Workbench
        2. Go to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: "Found in VS Code Extensions panel or `code --list-extensions --show-versions`"
      placeholder: "e.g. 1.2.0"
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: "Found via Help > About"
      placeholder: "e.g. 1.96.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: source-type
    attributes:
      label: NuGet Source Type
      description: Which type of NuGet feed are you using?
      options:
        - nuget.org only
        - Private feed only (e.g. GitLab, Azure Artifacts, GitHub Packages)
        - Both nuget.org and private feeds
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: |
        Paste any relevant error messages, output logs, or screenshots.
        Tip: Open the Webview Developer Tools (Ctrl+Shift+P > "Developer: Open Webview Developer Tools") to see console errors.
      render: text
    validations:
      required: false
