name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature suggestion! Please describe what you'd like to see.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature.
      placeholder: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: Why is this feature useful? What problem does it solve?
      placeholder: As a developer, I want to ... so that ...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this could be implemented? (optional)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered? (optional)
    validations:
      required: false
